name: novel
description: A new Flutter project.

version: 1.0.3+3

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_wallpaper_manager: ^0.0.4
  iconsax: ^0.0.8
  path_provider: ^2.0.14
  archive: ^3.3.7
  entry: ^0.0.8+1
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  flutter_cache_manager:
  permission_handler: ^10.2.0
  google_fonts: ^5.1.0
  provider: ^6.0.4
  photo_view: ^0.14.0
  palette_generator: ^0.3.3+2  
  rename: ^2.1.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1  
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.2
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.7




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/app elements/
