name: novel
description: A new Flutter project.

version: 1.0.6+6

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_wallpaper_manager: ^0.0.4
  iconsax: ^0.0.8
  path_provider: ^2.1.3
  archive: ^3.6.1
  entry: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_cache_manager: ^3.3.2
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  photo_view: ^0.15.0
  palette_generator: ^0.3.3+4
  rename: ^3.0.2
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.6
#  firebase_auth: ^4.6.1
#  google_sign_in: ^6.1.2
#  firebase_core: ^2.13.0
#  firebase_messaging: ^14.6.9
  external_app_launcher: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/app elements/
